# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  required_plugins = %w( vagrant-disksize vagrant-proxyconf vagrant-docker-compose )
  installed_plugins = 0
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      system("vagrant plugin install vagrant-docker-compose")
      installed_plugins += 1
    end
  end
  if installed_plugins > 0
    puts "Dependencies installed, please try the command again."
    exit
  end
  
  config.proxy.http = ENV['http_proxy']
  config.proxy.https = ENV['https_proxy']
  config.proxy.no_proxy = ENV['no_proxy']
  
  config.vm.define "larry" do |host|
    host.vm.box = "ubuntu/xenial64"
    host.vm.hostname = "larry"
    host.vm.network :private_network, ip: "10.10.10.11"
  
    host.vm.provider "virtualbox" do |v|
      v.name = "larry"
      v.memory = 512
      v.cpus = 1
    end

    host.vm.provision :docker do |d|
      d.pull_images "jamtur01/consul"
    end
  end
  
  config.vm.define "curly" do |host|
    host.vm.box = "ubuntu/xenial64"
    host.vm.hostname = "curly"
    host.vm.network :private_network, ip: "10.10.10.12"
  
    host.vm.provider "virtualbox" do |v|
      v.name = "curly"
      v.memory = 512
      v.cpus = 1
    end

    host.vm.provision :docker do |d|
      d.pull_images "jamtur01/consul"
    end
  end

  config.vm.define "moe" do |host|
    host.vm.box = "ubuntu/xenial64"
    host.vm.hostname = "moe"
    host.vm.network :private_network, ip: "10.10.10.13"
  
    host.vm.provider "virtualbox" do |v|
      v.name = "moe"
      v.memory = 512
      v.cpus = 1
    end

    host.vm.provision :docker do |d|
      d.pull_images "jamtur01/consul"
    end
  end
end